// Note: Admin Dashboard Layout
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Roboto } from "next/font/google";
import Nav from '../[id]/components/nav/nav';

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

import "tw-elements/dist/css/tw-elements.min.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Flight Reservation',
  description: 'Generated by create next app',
}

export default function AdmninLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>

        <Nav />
        {children}

      </body>
    </html>
  )
}
